# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: groceries
      MYSQL_USER: gracy
      MYSQL_PASSWORD: gracyspw

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080